# -*- coding: utf-8 -*-
"""Cyclopeptide sequencing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/154oAF8pO8MFNW14JhMdFaJh7megFxDy4
"""

from google.colab import drive
drive.mount('/content/drive')

#initial List
def initial_List(List):
  S_List=[]
  freqDic = {}
  for i in List:
    if(i > 186):
      break
    if (i == 0):
      continue
    a = wdict[i]
    S_List.append(a)
   
    if  (a in freqDic):
      freqDic[a] += 1
    else:
      freqDic[a] = 1
  return S_List,freqDic

#linear spectrum
def linearSpectrum(peptide):
    subList = [peptide]
    for i in range(len(peptide) - 1):
      for j in range(len(peptide)):
        if (i+j) < len(peptide):
          subList.append(peptide[j :j + i + 1])
              
    sumList = []
    #loop calculate weights for each element in the list
    for i in subList:
      sumList.append(weight(i))
    return sumList

def weight(subpeptide):
  total = 0
  for s in subpeptide:
    total += aadict[s]
  return total

#is consistant
def isConsistant(peptide):
  sumList = linearSpectrum(peptide)
  for i in sumList:
    if sumList.count(i) > List.count(i):
      return False
  return True

#append List
def peptideSequencing(intialList, freqDic):
  ln = len(intialList) - 1
  intialList = list(dict.fromkeys(intialList))
  consistantList = list(dict.fromkeys(intialList))
  for i in range(ln):
    tmpList = []
    for j in range(len(consistantList)):
      for k in range(len(intialList)):
        if freqDic[intialList[k]] > consistantList[j].count(intialList[k]):
          peptide = consistantList[j] + intialList[k]
          if isConsistant(peptide):
            tmpList.append(peptide)
    consistantList = tmpList.copy()
  return consistantList

#Main
file = open("/content/drive/MyDrive/Colab Notebooks/weight.txt")
file2 = open("/content/drive/MyDrive/Colab Notebooks/List.txt")
List = []
aadict={}
wdict={}
# read weights file and save data in dictionary
for f in file:
    line= f.rstrip()
    words=line.split(" ")
    aa = words[0]
    w = int(words[1])
    aadict[aa] = w
    wdict[w] = aa
# read Linear file and save data in dictionary
for f in file2:
  List = f.split(" ")

for i in range(0, len(List)):
  List[i] = int(List[i])

intial, freqDic = initial_List(List)
ans = peptideSequencing(intial, freqDic)
print(ans)

"""# New Section"""